return {
    ["argonian"]          = { player = "racial_argonian_power", npc = "racial_argonian_npc" },
    ["breton"]            = { player = "racial_breton_power", npc = "racial_breton_npc" },
    ["dark elf"]          = { player = "racial_darkelf_power", npc = "racial_darkelf_npc" },
    ["high elf"]          = { player = "racial_highelf_power", npc = "racial_highelf_npc" },
    ["imperial"]          = { player = "racial_imperial_power_2", npc = "racial_imperial_npc" },
    ["khajiit"]           = { player = "racial_khajiit_power", npc = "racial_khajiit_npc" },
    ["nord"]              = { player = "racial_nord_power", npc = "racial_nord_npc" },
    ["orc"]               = { player = "racial_orc_power", npc = "racial_orc_npc" },
    ["redguard"]          = { player = "racial_redguard_power", npc = "racial_redguard_npc" },
    ["wood elf"]          = { player = "racial_woodelf_power", npc = "racial_woodelf_npc" },
    ["t_cyr_ayleid"]      = { player = "racial_ayleid_power", npc = "racial_ayleid_npc" },
    ["t_els_cathay"]      = { player = "racial_khajiit_power", npc = "racial_khajiit_npc" },
    ["t_els_cathay-raht"] = { player = "racial_khajiit_power", npc = "racial_khajiit_npc" },
    ["t_els_dagi-raht"]   = { player = "racial_khajiit_power_3", npc = "racial_khajiit_npc_3" },
    ["t_els_ohmes"]       = { player = "racial_khajiit_power_2", npc = "racial_khajiit_npc_2" },
    ["t_els_ohmes-raht"]  = { player = "racial_khajiit_power_2", npc = "racial_khajiit_npc_2" },
    ["t_els_suthay"]      = { player = "racial_khajiit_power_2", npc = "racial_khajiit_npc_2" },
    ["t_cnq_chimeriquey"] = { player = "racial_chimeri_power", npc = "racial_chimeri_npc" },
    ["t_yok_duadri"]      = { player = "racial_duadri_power", npc = "racial_duadri_npc" },
    ["t_val_imga"]        = { player = "racial_imga_power", npc = "racial_imga_npc" },
    ["t_cnq_keptu"]       = { player = "racial_keptu_power", npc = "racial_keptu_npc" },
    ["t_sky_reachman"]    = { player = "racial_reachman_power", npc = "racial_reachman_npc" },
    ["t_hr_riverfolk"]    = { player = "racial_riverfolk_power", npc = "racial_riverfolk_npc" },
    ["t_pya_seaelf"]      = { player = "racial_seaelf_power", npc = "racial_seaelf_npc" },
    ["t_aka_tsaesci"]     = { player = "racial_tsaesci_power", npc = "racial_tsaesci_npc" },
    ["t_yne_ynesai"]      = { player = "racial_ynesai_power", npc = "racial_ynesai_npc" },
}
